### ISSUE TITLE
Bug: Couple of Off By 1 Results

### ISSUE THREAD

**Issue by Tree52** [zzzachzzz/toontown-combos#35]
https://youtu.be/ytp-IaN4ObQ?si=xAl8-Fbwc5al7AKi&t=699
Lure, 3 Seltzer (2 Org), Hose. 21, 25, 25, 30. 51 Orange. 21 Yellow. Total: 173.

![image](https://github.com/user-attachments/assets/62e7561f-11b2-42b1-8de3-d95946a28e36)

And

https://youtu.be/ytp-IaN4ObQ?si=apKsmyTVziATZEq6&t=117
Lure, Fruit, 3 Cream (1 Org). 27, 40, 40, 44. 76 Orange. 31 Yellow. Total: 258.

![image](https://github.com/user-attachments/assets/e6ec16ab-8782-40f7-922f-55319ec6220a)

Reading the damage function:
```
damage(cog?: Cog, onlyTrack?: GagTrack): number {
    return this.gagsGroupedByTrack().reduce((dmg, gags) => {
      if (onlyTrack && gags[0].track !== onlyTrack)
        return dmg;
      // If multiple traps are in the combo, they cancel each other out, don't included the trap damage
      if (gags[0].track === GagTracks.trap && gags.length >= 2)
        return dmg;
      return dmg + Math.ceil(
        gags.reduce((sumBaseDmgs, gag) => sumBaseDmgs + gag.damage, 0)
        * gags[0].multiplier(this, cog)
      );
    }, 0);
  }
```

I'm not entirely sure, but it seems to be doing 101 + ceil(101*.7) = 101 + 71 = 172. When it should do 101 + ceil(101*.5) + ceil(101*.2) = 173.

**Comment by zzzachzzz** [comment]
Wow, thank you so much for the thorough report. I will check this out
